#! /bin/sh
DOTS=$HOME/dotfiles

pgrep -x sxhkd >/dev/null || sxhkd &
nitrogen --restore &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &
sh $HOME/.config/polybar/launch.sh --rusty &

#set desktops
bspc monitor HDMI1 -d I II III IV V
bspc monitor eDP1 -d VI VII VIII IX X

##########################################################
#                      bspc config                       #
##########################################################

bspc config window_gap 10
bspc config top_padding 0
bspc config left_padding 14
bspc config right_padding 14
bspc config bottom_padding 14

bspc config split_ratio 0.55

bspc config border_width 0
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config single_monocle      false

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor false

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors false


# colors
source ~/.config/bspwm/theme

bspc rule -a Nitrogen state=floating
bspc rule -a Zathura state=tiled
bspc rule -a flameshot state=floating follow=on
bspc rule -a librewolf desktop='^6' follow=on
bspc rule -a dolphin desktop='^10' follow=on
