#! /bin/sh
#launch sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

#launch polybar
#bash $HOME/.config/polybar/launch.sh

#set desktops
bspc monitor HDMI1 -d I II III IV V
bspc monitor eDMI -d VI VII VIII IX X

#window settings
bspc config border_width 6
bspc config window_gap 20

bspc config split_ratio 0.55
bspc config borderless_monocle false
bspc config gapless_monocle false

# colors
source ~/.config/bspwm/theme

#window rules
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Gscreenshot state=floating follow=on
bspc rule -a firefox desktop='^6' follow=on
bspc rule -a dolphin desktop='^10' follow=on
bspc rule -a discord desktop='^2'
